version: '3'

services:
  user-managment:
    build:
      context: ./user-managment
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      PORT: 3000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - shared-data:/shared

  course-management:
    build:
      context: ./course-management
      dockerfile: Dockerfile
    ports:
      - "5060:5060"  
    environment:
      PORT: 5060
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - shared-data:/shared

  payment-management:
    build:
      context: ./payment-management
      dockerfile: Dockerfile
    ports:
      - "4040:4040"  
    environment:
      PORT: 4040
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - shared-data:/shared

volumes:
  shared-data:
