version: '3'

services:
  user-managment:
    build:
      context: ./user-managment
      dockerfile: Dockerfile
    ports:
      - "${USER_MANAGMENT_PORT}:5050" 
    environment:
      PORT: 5050
      MONGODB_URI: "mongodb+srv://imeshworkspace:root@cluster0.hlpymcv.mongodb.net/EduPulse?retryWrites=true&w=majority&appName=Cluster0"
      JWT_SECRET: "j5QYJQtGR2XtriOcAssSaGAf0YO1Cmv1"
    # depends_on:
    #   - mongo  # Dependency on MongoDB service

  course-management:
    build:
      context: ./course-management
      dockerfile: Dockerfile
    ports:
      - "${COURSE_MANAGEMENT_PORT}:7070"  
    environment:
      PORT: 7070
      MONGODB_URI: "mongodb+srv://imeshworkspace:root@cluster0.hlpymcv.mongodb.net/EduPulse?retryWrites=true&w=majority&appName=Cluster0"
      JWT_SECRET: "j5QYJQtGR2XtriOcAssSaGAf0YO1Cmv1"
    depends_on:
      # - mongo  # Dependency on MongoDB service

  payment-management:
    build:
      context: ./payment-management
      dockerfile: Dockerfile
    ports:
      - "${PAYMENT_MANAGEMENT_PORT}:9090"  
    environment:
      PORT: 9090
      MONGODB_URI: "mongodb+srv://imeshworkspace:root@cluster0.hlpymcv.mongodb.net/EduPulse?retryWrites=true&w=majority&appName=Cluster0"
      JWT_SECRET: "j5QYJQtGR2XtriOcAssSaGAf0YO1Cmv1"

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"  # Expose MongoDB port
  #   volumes:
  #     - mongodb_data:/data/db  # Persist MongoDB data

# volumes:
#   mongodb_data:
