version: '3'

services:
  user-managment:
    build:
      context: ./user-managment
      dockerfile: Dockerfile
    ports:
      - "5050:5050" 
    environment:
      PORT: 5050
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - shared-data:/shared

  course-management:
    build:
      context: ./course-management
      dockerfile: Dockerfile
    ports:
      - "7070:7070"  
    environment:
      PORT: 7070
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - shared-data:/shared

  payment-management:
    build:
      context: ./payment-management
      dockerfile: Dockerfile
    ports:
      - "9090:9090"  
    environment:
      PORT: 9090
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      API_KEY: ${API_KEY}
      DOMAIN: ${DOMAIN}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    volumes:
      - shared-data:/shared

volumes:
  shared-data:
